source 'https://rubygems.org'

gem 'rails'
gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.2.0'
  gem 'coffee-rails', '~> 3.2.0'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'realtime-validations', '~> 0.0.3'
